### ISSUE TITLE
3.34-rc2 ISO doesn't finish boot on the "tivo partitions" kernel

### ISSUE THREAD

**Issue by oom-is** [thess/mfstools#2] opened 2021-09-22 04:27 UTC
I was able to boot the "normal" kernel and run mfstools.
However, I had first tried the boot-menu option to boot the "tivo" kernel that should understand APM partitions.

Unfortunately it threw an error of the form /live/something was not valid and that I needed to load the kernel.
I'm guessing this is a known error, but wanted to document it.

System I'm booting this on is an older Asus MB with an AMD chip (Phenom), and it's booting from ISO-on-USB stick

**Comment by thess** [comment] 2021-09-22 13:09
Curious -- I will look into this. There is so little difference between the 2 kernels - only the APM partition recognizer is modified.

**Comment by thess** [comment] 2021-09-22 15:42
From the looks of the message you mentioned, the USB was probably has a missing or corrupted copy of one of the 2 necessary kernel boot files. I would verify that the ISO was imaged properly by whatever tool you used to make the USB. I have been using **balenaEtcher** lately (a free tool) with great success for a while now making bootable USBs on both Windows and Linux.

That said, the '/live/something' in the message will either be the kernel (vmlinuz) or initrd followed by a version identifier. Those files should be in the `/live` directory on your boot partition. 

I also booted a USB on an AMD Phenom system here without any problems.

**Comment by oom-is** [comment] 2021-09-23 02:58
I'll try with etcher to "burn" to a different small USB stick tomorrow and cross-check things.
I've used etcher previously and liked it, but for whatever reason was using some other random utility to make the bootable USB this time.
Thanks.

**Comment by thess** [comment] 2021-10-07 02:58
Closing - not a bug.

**Closed as completed by thess** 2021-10-07 02:58 UTC
